export interface ExampleSentence {
  zh: string
  en: string
}

const SENTENCES: Record<string, ExampleSentence> = {
  '爱': { zh: '我爱我的家人。', en: 'I love my family.' },
  '爸爸': { zh: '我爸爸很高。', en: 'My dad is tall.' },
  '杯子': { zh: '这个杯子是我的。', en: 'This cup is mine.' },
  '北京': { zh: '北京是中国的首都。', en: 'Beijing is the capital of China.' },
  '不': { zh: '我不喝咖啡。', en: "I don't drink coffee." },
  '不客气': { zh: '"谢谢！""不客气！"', en: '"Thank you!" "You\'re welcome!"' },
  '菜': { zh: '这个菜很好吃。', en: 'This dish is very tasty.' },
  '茶': { zh: '我喜欢喝茶。', en: 'I like drinking tea.' },
  '吃': { zh: '你吃早饭了吗？', en: 'Did you eat breakfast?' },
  '出租车': { zh: '我坐出租车去机场。', en: 'I take a taxi to the airport.' },
  '大': { zh: '这个房间很大。', en: 'This room is very big.' },
  '的': { zh: '这是我的书。', en: 'This is my book.' },
  '点': { zh: '现在三点了。', en: "It's 3 o'clock now." },
  '电脑': { zh: '我用电脑工作。', en: 'I work on a computer.' },
  '电视': { zh: '我每天晚上看电视。', en: 'I watch TV every evening.' },
  '电影': { zh: '这部电影很好看。', en: 'This movie is very good.' },
  '东西': { zh: '我买了很多东西。', en: 'I bought many things.' },
  '都': { zh: '我们都喜欢中国菜。', en: 'We all like Chinese food.' },
  '读': { zh: '我喜欢读书。', en: 'I like reading.' },
  '对不起': { zh: '对不起，我来晚了。', en: "Sorry, I'm late." },
  '多': { zh: '这里有很多人。', en: 'There are many people here.' },
  '多少': { zh: '这个多少钱？', en: 'How much is this?' },
  '饿': { zh: '我很饿，想吃东西。', en: "I'm hungry and want to eat something." },
  '儿子': { zh: '他有一个儿子。', en: 'He has a son.' },
  '饭店': { zh: '我们在饭店吃饭。', en: "We're eating at the restaurant." },
  '高兴': { zh: '见到你真高兴！', en: 'So happy to see you!' },
  '工作': { zh: '他的工作很忙。', en: 'His work is very busy.' },
  '狗': { zh: '我有一只狗。', en: 'I have a dog.' },
  '汉语': { zh: '我在学汉语。', en: "I'm learning Chinese." },
  '好': { zh: '今天天气很好。', en: "Today's weather is very nice." },
  '好吃': { zh: '这个菜真好吃！', en: 'This dish is really delicious!' },
  '喝': { zh: '你想喝什么？', en: 'What would you like to drink?' },
  '和': { zh: '我和朋友一起去。', en: "I'm going together with my friend." },
  '很': { zh: '这本书很有意思。', en: 'This book is very interesting.' },
  '后面': { zh: '学校在银行后面。', en: "The school is behind the bank." },
  '回': { zh: '我下午回家。', en: 'I go home in the afternoon.' },
  '会': { zh: '你会说中文吗？', en: 'Can you speak Chinese?' },
  '叫': { zh: '我叫小明。', en: 'My name is Xiaoming.' },
  '今天': { zh: '今天天气真好！', en: "The weather is really nice today!" },
  '开': { zh: '请开门。', en: 'Please open the door.' },
  '看': { zh: '我在看书。', en: "I'm reading a book." },
  '看见': { zh: '我看见他了。', en: 'I saw him.' },
  '来': { zh: '你什么时候来？', en: 'When are you coming?' },
  '老师': { zh: '我的老师很好。', en: 'My teacher is very nice.' },
  '冷': { zh: '今天很冷。', en: "It's cold today." },
  '里': { zh: '猫在房间里。', en: 'The cat is inside the room.' },
  '妈妈': { zh: '我妈妈会做菜。', en: 'My mom can cook.' },
  '猫': { zh: '这只猫很可爱。', en: 'This cat is very cute.' },
  '没关系': { zh: '"对不起！""没关系。"', en: '"Sorry!" "It\'s okay."' },
  '没有': { zh: '我没有手机。', en: "I don't have a phone." },
  '米饭': { zh: '我喜欢吃米饭。', en: 'I like eating rice.' },
  '明天': { zh: '明天见！', en: 'See you tomorrow!' },
  '名字': { zh: '你的名字叫什么？', en: 'What is your name?' },
  '哪': { zh: '你是哪国人？', en: 'Which country are you from?' },
  '那': { zh: '那个人是谁？', en: 'Who is that person?' },
  '年': { zh: '今年天气很热。', en: 'The weather this year is very hot.' },
  '女儿': { zh: '她有一个女儿。', en: 'She has a daughter.' },
  '朋友': { zh: '他是我的好朋友。', en: 'He is my good friend.' },
  '漂亮': { zh: '她今天很漂亮。', en: 'She looks very pretty today.' },
  '苹果': { zh: '我喜欢吃苹果。', en: 'I like eating apples.' },
  '钱': { zh: '你有多少钱？', en: 'How much money do you have?' },
  '前面': { zh: '学校前面有一家店。', en: "There's a shop in front of the school." },
  '请': { zh: '请进！', en: 'Please come in!' },
  '去': { zh: '你去哪里？', en: 'Where are you going?' },
  '热': { zh: '今天太热了。', en: "It's too hot today." },
  '人': { zh: '这里有很多人。', en: 'There are many people here.' },
  '认识': { zh: '很高兴认识你！', en: 'Nice to meet you!' },
  '三': { zh: '我有三个苹果。', en: 'I have three apples.' },
  '商店': { zh: '商店几点开门？', en: 'What time does the shop open?' },
  '上': { zh: '书在桌子上。', en: 'The book is on the desk.' },
  '上午': { zh: '我上午学习，下午休息。', en: 'I study in the morning and rest in the afternoon.' },
  '少': { zh: '今天人很少。', en: 'There are very few people today.' },
  '谁': { zh: '那个人是谁？', en: 'Who is that person?' },
  '什么': { zh: '你叫什么名字？', en: 'What is your name?' },
  '生日': { zh: '今天是我的生日。', en: 'Today is my birthday.' },
  '时候': { zh: '你什么时候来？', en: 'When are you coming?' },
  '是': { zh: '我是学生。', en: 'I am a student.' },
  '书': { zh: '这本书很有意思。', en: 'This book is very interesting.' },
  '水': { zh: '我想喝水。', en: 'I want to drink water.' },
  '水果': { zh: '我每天吃水果。', en: 'I eat fruit every day.' },
  '睡觉': { zh: '我十点睡觉。', en: 'I go to sleep at 10 o\'clock.' },
  '说': { zh: '他说中文说得很好。', en: 'He speaks Chinese very well.' },
  '说话': { zh: '他说话很快。', en: 'He speaks very fast.' },
  '他': { zh: '他是我的老师。', en: 'He is my teacher.' },
  '她': { zh: '她是我的妈妈。', en: 'She is my mother.' },
  '太': { zh: '今天太热了！', en: "It's too hot today!" },
  '天气': { zh: '今天天气怎么样？', en: "How's the weather today?" },
  '听': { zh: '我喜欢听音乐。', en: 'I like listening to music.' },
  '同学': { zh: '他是我的同学。', en: 'He is my classmate.' },
  '我': { zh: '我是中国人。', en: 'I am Chinese.' },
  '我们': { zh: '我们是好朋友。', en: 'We are good friends.' },
  '下': { zh: '猫在桌子下面。', en: 'The cat is under the table.' },
  '下午': { zh: '我下午去看电影。', en: "I'm going to see a movie this afternoon." },
  '下雨': { zh: '今天下雨了。', en: 'It rained today.' },
  '现在': { zh: '现在几点了？', en: 'What time is it now?' },
  '想': { zh: '我想吃苹果。', en: 'I want to eat an apple.' },
  '小': { zh: '这只猫很小。', en: 'This cat is very small.' },
  '写': { zh: '请写你的名字。', en: 'Please write your name.' },
  '谢谢': { zh: '谢谢你的帮助！', en: 'Thank you for your help!' },
  '星期': { zh: '今天是星期几？', en: 'What day of the week is it today?' },
  '学生': { zh: '他是大学生。', en: 'He is a university student.' },
  '学习': { zh: '我每天学习中文。', en: 'I study Chinese every day.' },
  '学校': { zh: '我每天去学校。', en: 'I go to school every day.' },
  '衣服': { zh: '我买了一件衣服。', en: 'I bought a piece of clothing.' },
  '医生': { zh: '他是一位好医生。', en: 'He is a good doctor.' },
  '医院': { zh: '我去医院看病。', en: 'I went to the hospital to see a doctor.' },
  '椅子': { zh: '请坐在椅子上。', en: 'Please sit on the chair.' },
  '有': { zh: '我有一个哥哥。', en: 'I have an older brother.' },
  '月': { zh: '我生日在三月。', en: 'My birthday is in March.' },
  '再见': { zh: '再见，明天见！', en: 'Goodbye, see you tomorrow!' },
  '在': { zh: '我在家学习。', en: "I'm studying at home." },
  '怎么': { zh: '怎么去火车站？', en: 'How do I get to the train station?' },
  '怎么样': { zh: '你最近怎么样？', en: 'How have you been lately?' },
  '这': { zh: '这是我的书包。', en: 'This is my backpack.' },
  '中国': { zh: '我在中国学习汉语。', en: "I'm studying Chinese in China." },
  '中午': { zh: '中午我和同学吃饭。', en: 'At noon I eat with my classmates.' },
  '住': { zh: '我住在北京。', en: 'I live in Beijing.' },
  '桌子': { zh: '书在桌子上。', en: 'The book is on the desk.' },
  '字': { zh: '这个字怎么写？', en: 'How do you write this character?' },
  '坐': { zh: '我坐火车去上海。', en: 'I take the train to Shanghai.' },
  '做': { zh: '我在做作业。', en: "I'm doing my homework." },
  // HSK 2
  '吧': { zh: '我们走吧。', en: "Let's go." },
  '帮助': { zh: '谢谢你帮助我。', en: 'Thank you for helping me.' },
  '比': { zh: '今天比昨天热。', en: 'Today is hotter than yesterday.' },
  '别': { zh: '别担心！', en: "Don't worry!" },
  '长': { zh: '这条路很长。', en: 'This road is very long.' },
  '唱歌': { zh: '她喜欢唱歌。', en: 'She likes singing.' },
  '出': { zh: '他出门了。', en: 'He went out.' },
  '穿': { zh: '她穿了一件红衣服。', en: 'She wore a red dress.' },
  '次': { zh: '我去过两次中国。', en: 'I have been to China twice.' },
  '从': { zh: '我从家走到学校。', en: 'I walk from home to school.' },
  '错': { zh: '对不起，我写错了。', en: "Sorry, I wrote it wrong." },
  '打电话': { zh: '我给妈妈打电话。', en: 'I called my mom.' },
  '大家': { zh: '大家好！', en: 'Hello everyone!' },
  '但是': { zh: '我想去，但是太忙了。', en: "I want to go, but I'm too busy." },
  '地方': { zh: '这是一个好地方。', en: 'This is a nice place.' },
  '等': { zh: '请等一下。', en: 'Please wait a moment.' },
  '弟弟': { zh: '我弟弟今年十岁。', en: 'My younger brother is ten years old.' },
  '第一': { zh: '他是第一名。', en: 'He is first place.' },
  '懂': { zh: '你懂我说的吗？', en: 'Do you understand what I said?' },
  '对': { zh: '你说得对。', en: "What you said is right." },
  '房间': { zh: '这个房间很干净。', en: 'This room is very clean.' },
  '非常': { zh: '今天非常热。', en: "It's extremely hot today." },
  '服务员': { zh: '服务员，买单！', en: 'Waiter, the bill please!' },
  '高': { zh: '他很高，超过一米八。', en: 'He is very tall, over 1.8 meters.' },
  '告诉': { zh: '请告诉我你的地址。', en: 'Please tell me your address.' },
  '哥哥': { zh: '我哥哥在北京工作。', en: 'My older brother works in Beijing.' },
  '给': { zh: '我给你一本书。', en: 'I give you a book.' },
  '跟': { zh: '我跟朋友一起去。', en: "I'm going with my friend." },
  '公共汽车': { zh: '我坐公共汽车上班。', en: 'I take the bus to work.' },
  '公司': { zh: '他在大公司工作。', en: 'He works at a big company.' },
  '贵': { zh: '这件衣服太贵了。', en: 'This piece of clothing is too expensive.' },
  '过': { zh: '我去过日本。', en: 'I have been to Japan.' },
  '还': { zh: '我还没吃饭。', en: "I haven't eaten yet." },
  '还是': { zh: '你喝茶还是咖啡？', en: 'Would you like tea or coffee?' },
  '孩子': { zh: '这个孩子很聪明。', en: 'This child is very smart.' },
  '好看': { zh: '这部电影很好看。', en: 'This movie is very good.' },
  '黑': { zh: '我有一件黑衣服。', en: 'I have a black piece of clothing.' },
  '红': { zh: '她穿了一件红裙子。', en: 'She wore a red skirt.' },
  '欢迎': { zh: '欢迎来中国！', en: 'Welcome to China!' },
  '还有': { zh: '还有什么问题？', en: 'Are there any more questions?' },
  '火车站': { zh: '火车站在哪里？', en: 'Where is the train station?' },
  '机场': { zh: '我去机场接他。', en: 'I went to the airport to pick him up.' },
  '鸡蛋': { zh: '我早上吃了两个鸡蛋。', en: 'I ate two eggs in the morning.' },
  '件': { zh: '我买了一件衬衫。', en: 'I bought a shirt.' },
  '教室': { zh: '同学们在教室里学习。', en: 'Students are studying in the classroom.' },
  '介绍': { zh: '请介绍一下你自己。', en: 'Please introduce yourself.' },
  '进': { zh: '请进！', en: 'Please come in!' },
  '近': { zh: '学校离我家很近。', en: 'The school is very close to my home.' },
  '就': { zh: '我就住在这里。', en: 'I live right here.' },
  '觉得': { zh: '我觉得这个电影很好。', en: 'I think this movie is very good.' },
  '可以': { zh: '我可以帮你。', en: 'I can help you.' },
  '可能': { zh: '他可能在家。', en: 'He might be at home.' },
  '快': { zh: '你走得太快了。', en: 'You walk too fast.' },
  '快乐': { zh: '祝你生日快乐！', en: 'Happy birthday to you!' },
  '离': { zh: '学校离这里不远。', en: "The school isn't far from here." },
  '脸': { zh: '她的脸很漂亮。', en: 'Her face is very pretty.' },
  '两': { zh: '我有两个哥哥。', en: 'I have two older brothers.' },
  '路': { zh: '这条路很长。', en: 'This road is very long.' },
  '旅游': { zh: '我喜欢去旅游。', en: 'I like to travel.' },
  '买': { zh: '我去买东西。', en: "I'm going to buy things." },
  '卖': { zh: '这家店卖很多东西。', en: 'This shop sells many things.' },
  '慢': { zh: '请说慢一点。', en: 'Please speak a bit slower.' },
  '忙': { zh: '最近我很忙。', en: "I've been very busy lately." },
  '每': { zh: '我每天喝水。', en: 'I drink water every day.' },
  '妹妹': { zh: '我妹妹很可爱。', en: 'My younger sister is very cute.' },
  '门': { zh: '请关门。', en: 'Please close the door.' },
  '面条': { zh: '我喜欢吃面条。', en: 'I like eating noodles.' },
  '那么': { zh: '他那么聪明，一定会成功。', en: "He's so smart, he'll definitely succeed." },
  '男': { zh: '他是男生。', en: 'He is a boy.' },
  '您': { zh: '您好，请问……', en: 'Hello, may I ask...' },
  '牛奶': { zh: '我每天喝一杯牛奶。', en: 'I drink a glass of milk every day.' },
  '女': { zh: '她是女生。', en: 'She is a girl.' },
  '旁边': { zh: '银行在学校旁边。', en: 'The bank is next to the school.' },
  '跑步': { zh: '我每天早上跑步。', en: 'I go running every morning.' },
  '便宜': { zh: '这件衣服很便宜。', en: 'This piece of clothing is very cheap.' },
  '票': { zh: '我买了两张电影票。', en: 'I bought two movie tickets.' },
  '妻子': { zh: '他的妻子很漂亮。', en: 'His wife is very pretty.' },
  '起床': { zh: '我每天七点起床。', en: 'I get up at 7 o\'clock every day.' },
  '千': { zh: '这本书要一千块。', en: 'This book costs one thousand yuan.' },
  '晴': { zh: '今天天气晴。', en: "Today's weather is sunny." },
  '让': { zh: '他让我等一下。', en: 'He asked me to wait a moment.' },
  '然后': { zh: '我先吃饭，然后去散步。', en: 'I eat first, then go for a walk.' },
  '如果': { zh: '如果你来，我很高兴。', en: "If you come, I'd be very happy." },
  '身体': { zh: '身体健康最重要。', en: 'Good health is most important.' },
  '生病': { zh: '我昨天生病了。', en: 'I was sick yesterday.' },
  '生气': { zh: '他很生气。', en: 'He is very angry.' },
  '时间': { zh: '你有时间吗？', en: 'Do you have time?' },
  '事情': { zh: '这件事情很重要。', en: 'This matter is very important.' },
  '手': { zh: '请举手！', en: 'Please raise your hand!' },
  '手机': { zh: '我的手机没电了。', en: 'My phone has run out of battery.' },
  '瘦': { zh: '她比以前瘦了。', en: 'She is thinner than before.' },
  '虽然': { zh: '虽然很难，但我坚持。', en: "Although it's difficult, I persist." },
  '所以': { zh: '我病了，所以没来。', en: "I was sick, so I didn't come." },
  '甜': { zh: '这个苹果很甜。', en: 'This apple is very sweet.' },
  '踢足球': { zh: '他喜欢踢足球。', en: 'He likes playing football.' },
  '题': { zh: '这道题很难。', en: 'This problem is very difficult.' },
  '跳舞': { zh: '她喜欢跳舞。', en: 'She likes dancing.' },
  '外': { zh: '外面很冷。', en: "It's cold outside." },
  '玩': { zh: '孩子们在外面玩。', en: 'The children are playing outside.' },
  '晚上': { zh: '晚上好！', en: 'Good evening!' },
  '往': { zh: '往右走。', en: 'Walk to the right.' },
  '为什么': { zh: '你为什么不来？', en: "Why didn't you come?" },
  '问': { zh: '我想问你一个问题。', en: 'I want to ask you a question.' },
  '问题': { zh: '我有一个问题。', en: 'I have a question.' },
  '西瓜': { zh: '夏天我喜欢吃西瓜。', en: 'I like eating watermelon in summer.' },
  '希望': { zh: '我希望你健康快乐。', en: 'I hope you are healthy and happy.' },
  '洗': { zh: '我去洗手。', en: "I'm going to wash my hands." },
  '先': { zh: '你先说吧。', en: 'You go first.' },
  '姐姐': { zh: '我姐姐比我大三岁。', en: 'My older sister is three years older than me.' },
  '新': { zh: '这是我的新书包。', en: 'This is my new backpack.' },
  '行李箱': { zh: '我的行李箱很重。', en: 'My suitcase is very heavy.' },
  '兴趣': { zh: '我对音乐很有兴趣。', en: 'I have a great interest in music.' },
  '休息': { zh: '我想休息一下。', en: 'I want to rest for a while.' },
  '需要': { zh: '你需要帮助吗？', en: 'Do you need help?' },
  '选择': { zh: '我不知道怎么选择。', en: "I don't know how to choose." },
  '眼睛': { zh: '她的眼睛很大。', en: 'Her eyes are very big.' },
  '要': { zh: '我要一杯水。', en: 'I want a glass of water.' },
  '也': { zh: '我也喜欢喝茶。', en: 'I also like drinking tea.' },
  '已经': { zh: '我已经吃了。', en: "I've already eaten." },
  '一起': { zh: '我们一起走吧。', en: "Let's walk together." },
  '一直': { zh: '他一直在努力学习。', en: 'He has been studying hard all along.' },
  '游泳': { zh: '夏天我喜欢游泳。', en: 'I like swimming in the summer.' },
  '有名': { zh: '北京烤鸭很有名。', en: 'Peking duck is very famous.' },
  '右边': { zh: '银行在右边。', en: 'The bank is on the right side.' },
  '鱼': { zh: '我喜欢吃鱼。', en: 'I like eating fish.' },
  '远': { zh: '学校离这里很远。', en: 'The school is far from here.' },
  '运动': { zh: '我每天做运动。', en: 'I exercise every day.' },
  '再': { zh: '请再说一遍。', en: 'Please say it again.' },
  '早上': { zh: '早上好！', en: 'Good morning!' },
  '站': { zh: '我在车站等你。', en: "I'm waiting for you at the station." },
  '找': { zh: '我找不到我的钥匙。', en: "I can't find my key." },
  '着': { zh: '他穿着一件红衣服。', en: 'He is wearing a red piece of clothing.' },
  '正在': { zh: '我正在吃饭。', en: "I'm currently eating." },
  '知道': { zh: '你知道他在哪里吗？', en: 'Do you know where he is?' },
  '中间': { zh: '银行在超市中间。', en: 'The bank is in the middle of the supermarket.' },
  '重要': { zh: '这件事很重要。', en: 'This matter is very important.' },
  '终于': { zh: '我终于完成了！', en: 'I finally finished!' },
  '左边': { zh: '学校在左边。', en: 'The school is on the left side.' },
}

export function getSentence(simplified: string): ExampleSentence | null {
  return SENTENCES[simplified] ?? null
}
