[build]
  command = "pnpm install && pnpm build:words-db && pnpm --filter client build"
  publish = "client/dist"

[build.environment]
  VITE_BUILD_ID = "$COMMIT_REF"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/words.db"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sql-wasm.wasm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
